### ISSUE TITLE
Linter errors after upgradind dependencies

### ISSUE THREAD

**Issue by piranna** [Root-App/react-native-mock-render#21]
I've upgraded project dependencies and it shows a lot of linting errors, probably due to the update of the `elint-config-airbnb` dependency from `9.0.1` to `16.1.0`. When reverting to the currently ones defined on `package.json`, tests pass successfully.

**Comment by jimmy-devine** [comment]
Closing this issue for now. We'll look at this when we upgrade dependencies.
