### ISSUE TITLE
Breaks jest-expo

### ISSUE THREAD

**Issue by lropero** [Root-App/react-native-mock-render#33]
When using _jest-expo_ as a preset for Jest (I'm working on a detached Expo project, _jic_) and then trying to use _react-native-mock-render_ by adding this line to my Jest config file:
```
jest.mock('react-native', () => require('react-native-mock-render'), { virtual: true });
```

This error occurs when running my tests:
> The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo.

The failing check is at **node_modules/expo/src/environment/validate.js**:
```
if (!NativeModules.ExponentConstants) {
  throw new Error(ERROR_PASTED_ABOVE);
}
```

I believe this happens because both libraries are mocking _react-native_ in a non-`Object.assign(rn, rn1, rn2)`-form.

Couldn't both libraries work together somehow? I believe this would allow things like mounting (as opposed to shallowing) with _enzyme_, _jsdom_, and _react-native-mock-render_ on test suites.

**Comment by lropero** [comment]
btw this is in my **packages.json**:
```
"jest": {
  "preset": "jest-expo",
  "setupFiles": [
    "<rootDir>/jestConfig.js"
  ],
  "timers": "fake",
  "transformIgnorePatterns": []
},
```

**Comment by cantide5ga** [comment]
Wondering how relevant this is on [detachment](https://docs.expo.io/versions/latest/expokit/detach), but currently this is important to me too.

Thanks for the homework @lropero - interested if any project maintainers have any hints on your comments/suggestions?

**Comment by AlexCatch** [comment]
This is also an issue for me

**Comment by bob-carson** [comment]
I believe you could implement something custom by creating your own version of [mock.js](https://github.com/Root-App/react-native-mock-render/blob/master/mock.js) and/or [react-native.js](https://github.com/Root-App/react-native-mock-render/blob/master/src/react-native.js) that did the mixing and matching in the way that you wanted.

Unfortunately, this is out of scope of what this package is intended to do right now.  I'm going to go ahead and close this issue, but if you have any suggested code changes that would make that work easier for you or add to this project in a way that would make it support your use case I'm happy to review and merge your PR.
