### ISSUE TITLE
I can't simulate an event

### ISSUE THREAD

**Issue by dabit1** [Root-App/react-native-mock-render#35]
Hi guys! 

I'm trying to simulate the event `onValueChange` from Switch but I receive this when I use mount() (shallow is working):

`TypeError: ReactWrapper::simulate() event 'valueChange' does not exist`

And this is what I wrote:

```javascript 
const filter = wrapper.find(Filter).at(itemIndex)
filter.find('Switch').simulate('valueChange') 
```

Any idea?

Many thanks!

**Comment by TAGraves** [comment]
Check out the upstream issue at https://github.com/airbnb/enzyme/issues/1341. Enzyme can't currently simulate events it doesn't know about when using `mount()`. You can accomplish the same thing you're trying to do with `filter.find('Switch').props().onValueChange()`, passing in an event object you create as needed.

**Comment by dabit1** [comment]
This is what I did but it does not seem a nice solution when for `shallow` I call simulate() and for `mount` I call the prop. 

Thanks @TAGraves
