### ISSUE TITLE
How to test disabled property?

### ISSUE THREAD

**Issue by Victorien-Tardif** [Root-App/react-native-mock-render#59]
I'd like to test if my `<TouchableOpacity />` is actually disabled but I don't know how. 
I'm aware of how to test props but in case of a "disabled" prop, I don't really want to test if the prop is passed but if the button is actually disabled.

How could I do that? 

With a React component I would do 
```
const wrapper = mount(
  <Button disabled>
    Title
  </Button>,
);
expect(
  wrapper
    .find('button')
    .getDOMNode()
    .disabled,
).to.be.true;
```
but I can't find a way to test a react-native component.

Thanks!

**Comment by Quadriphobs1** [comment]
This thread explains how to disabled to `<TouchableOpacity />` https://stackoverflow.com/questions/33407665/disabling-buttons-on-react-native

**Comment by Victorien-Tardif** [comment]
Ok thanks, I wondered if there was a way to test if the button is actually disabled and not only if it has the prop disabled but I guess this is not my job but React-Native job to test that :) As long as the `<TouchableOpacity />` has prop disabled I think I can be confident with the fact it is disabled :)
