### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by jhilden** [Root-App/react-native-mock-render#6]
Thanks a lot for your library.  I think this is exactly what I have been looking for.  I also had the problem you are describeing in your [blog post](https://blog.joinroot.com/mounting-react-native-components-with-enzyme-and-jsdom/) that using `shallow` rendering is often not sufficient for testing RN components.

I tried using your library but unfortunately I wasn't able to get it to work (yet).

I think I have a pretty standard jest+RN setup, but I wouldn't know what (or where) my ` file-that-runs-before-all-of-my-tests.js` could be.

I tried just inserting the `require('react-native-mock-render/mock')` into my individual component test, but that simply led to issues such as
```
console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
    Warning: Unknown props `keyboardType`, `secureTextEntry`, `underlineColorAndroid`, `selectionColor`, `onChangeText`, `multiline`, `numberOfLines`, `blurOnSubmit`, `onSubmitEditing`, `returnKeyType` on <TextInput> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```
Seem like this is *not* coming from the mock implementation.  Do you happen to have any idea for me how to properly require your library when using jest?

----

Before that I also had the error message `ReferenceError: document is not defined` but that was solved by adding 

```
import {jsdom} from 'jsdom'

global.document = jsdom('')
global.window = document.defaultView
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    global[property] = document.defaultView[property]
  }
})
```
Just as you are describing in your blog post.  I think it would be very good to also add this to the README of this library.

**Comment by dan-manges** [comment]
Hi Jakob! We run our tests with mocha and have a shared setup file. In our `package.json` we have:

```json
{
  "name": "root-react-native",
  "scripts": {
    "test": "./node_modules/.bin/mocha --require test/setup-tests.js --recursive test",
  }
}
```

Then we put `require('react-native-mock-render/mock')` and our `jsdom` setup in our `test/setup-tests.js` file.

**Comment by dan-manges** [comment]
I accidentally posted too soon. Are you using `jest.mock` in your tests? We haven't tried using jest specifically. Could you share one of your tests?

**Comment by jhilden** [comment]
So, I figured out how to include a test setup script that runs before the test suite with jest:

in the `package.json` I added:
```
"jest": {
  "preset": "react-native",
  "setupFiles": ["<rootDir>/src/test/setup.js"]
},
```

```
// src/test/setup.js
console.log('setup test env')

require('react-native-mock-render/mock')

import {jsdom} from 'jsdom'

global.document = jsdom('')
global.window = document.defaultView
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    global[property] = document.defaultView[property]
  }
})
```

The setup script is executed correctly, but my component test is still failing with the same `Warning: Unknown props` error messages.

> Are you using jest.mock in your tests? 

In this particular component test I'm not using `jest.mock`

----

Btw:  I'm also getting an `TypeError: ReactWrapper::simulate() event 'press' does not exist` error.  I am using this in my test:
```
const submitButton = wrapper.find(Button)
submitButton.simulate('press')
```

**Comment by dan-manges** [comment]
@jhilden is your component getting mounted? You can check with:

```javascript
console.log(wrapper.debug());
```

If that looks good, is it finding the submit button successfully? You should be able to check with `console.log(submitButton.debug());`. Could you also try calling `submitButton.props().onPress();` to see if that works? We've had some issues using `simulate` on a mounted component and ended up calling functions on the props directly.

**Comment by andriichernenko** [comment]
I am also getting a lot of similar warnings:
```
  console.error jest/setup.js:43
    Warning: Unknown props `onLayout`, `keyboardVerticalOffset` on <View> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
        in View (created by View)
        in View (created by KeyboardAvoidingView)
        in KeyboardAvoidingView (created by _LoginView)
        in View (created by View)
        in View (created by _LoginView)
        in _LoginView (created by Connect(_LoginView))
        in Connect(_LoginView) (created by _RootView)
        in _RootView (created by Connect(_RootView))
        in Connect(_RootView)
        in Provider (created by Unknown)
        in Unknown
```
In my case, however, tests work.

As a workaround, I patched `console.error` to ignore these messages (as suggested [here](https://codereview.stackexchange.com/a/156374)):
```javascript
const originalConsoleError = console.error;
console.error = (message) => {
	if (message.startsWith('Warning: Unknown prop')) {
		return;
	}

	originalConsoleError(message);
};
```

**Comment by ryanhomer** [comment]
It seems that react-native-mock is not fully compatible with Jest according to [this post](https://github.com/RealOrangeOne/react-native-mock/issues/126#issuecomment-287135388).

I'm also getting a bunch of those missing props. I'm going to work with this for a bit to see how far I can get. So far, I'm still unable to render a ListView properly as part of my component tree that I'm interested in testing.

I'm hoping to not have to switch to and learn mocha + chai + sinon, etc. just yet as I like that the Jest framework encompasses most of this functionality already.

**Comment by kyledecot** [comment]
Hi @jhilden! I've been attempting to look into the issue that you and the others are facing but so far I'm unable to reproduce the issue. I've create a basic boilerplate project [here](https://github.com/kyledecot/react-native-mock-render-example). Would it be possible for you to fork this and see if you can reproduce the issue?

**Comment by jhilden** [comment]
Sorry @kyledecot but I have moved on to a different project, so it's unlikely that I will find the time to jump back to that issue.
