### ISSUE TITLE
Fix type for 'ItemSeparatorComponent' prop of 'FlatList'

### ISSUE THREAD

**Issue by jgarrone** [Root-App/react-native-mock-render#69]
https://github.com/Root-App/react-native-mock-render/blob/315e5b6471e937a8fad91a90777a1c879a6989e6/src/components/FlatList.js#L39
This is currently throwing a warning when running some tests:
```  console.error node_modules/prop-types/checkPropTypes.js:20
    Warning: Failed prop type: Invalid prop `ItemSeparatorComponent` of type `function` supplied to `FlatList`, expected a single ReactElement.
```
The type should be a component type or similar [(doc)](https://facebook.github.io/react-native/docs/flatlist.html#itemseparatorcomponent).

**Comment by IsaacSmith13** [comment]
This is fixed by https://github.com/Root-App/react-native-mock-render/pull/81, so I'm closing it
